service: io-node-challenge
provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage,'DESA'}
  region: us-east-2
  timeout: 60
plugins:
  - serverless-plugin-typescript
  - serverless-offline
package:
  individually: true
  exclude:
    - npm-cache/**
functions: ${file(config/functions.yaml)}