service: io-node-challenge
provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage,'DESA'}
  region: us-east-2
  timeout: 60
custom:
  reducer:
    ignoreMissing: true
plugins:
  - serverless-plugin-typescript
  - serverless-offline
  - serverless-plugin-reducer
package:
  individually: true
  exclude:
    - npm-cache/**
functions: ${file(config/functions.yaml)}