seedUsersTable:
  table: TABLE_${self:provider.stage}_USERS
  sources:
    - config/seeders/${self:provider.stage}/users/seed-user-1.json
    - config/seeders/${self:provider.stage}/users/seed-user-2.json