payments:
  handler: src/Payments/Infrastructure/AppLambda.handler
  name: LMB_${self:provider.stage}_PAYMENTS
transactions:
  handler: src/Transactions/Infrastructure/AppLambda.handler
  name: LMB_${self:provider.stage}_TRANSACTIONS
  events:
    - http:
        method: GET
        path: 'V1/transactions/{id}'
# Comentar la siguiente function 'activities' en el primer despliegue
# luego descomentar y volver a desplegar
activities:
  handler: src/Activities/Infrastructure/AppLambda.handler
  name: LMB_${self:provider.stage}_ACTIVITIES
  events:
    - stream:
        type: dynamodb
        batchSize: 1
        startingPosition: LATEST
        arn: ${fetchStreamARN(${self:provider.environment.DYNAMODB_TABLE_TRANSACTIONS})}
