Resources:
  DynamoDBUsersTable: ${file(config/dynamodb-tables.yaml):usersTable}
  DynamoDBTransactionsTable: ${file(config/dynamodb-tables.yaml):transactionsTable}
  DynamoDBActivityTable: ${file(config/dynamodb-tables.yaml):ActivityTable}